Traceback (most recent call last):
  File "C:\Users\larsenyg\AppData\Local\Programs\Python\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\larsenyg\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\larsenyg\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\larsenyg\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\larsenyg\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\larsenyg\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\larsenyg\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\larsenyg\AppData\Local\Programs\Python\Python310\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import pandas as pd 

ordinates = pd.read_csv('ordinates.csv', sep=" " )

lengdepos = [0 , 1 , 2 , 3 , 4 ,5 , 6 , 7 , 8, 9, 10, 11]

y_pos = [37 , 32 , 28 , 20 , 11 , 3 , 0]

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn [2], line 1[0m
[1;32m----> 1[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m 
[0;32m      3[0m ordinates [38;5;241m=[39m pd[38;5;241m.[39mread_csv([38;5;124m'[39m[38;5;124mordinates.csv[39m[38;5;124m'[39m, sep[38;5;241m=[39m[38;5;124m"[39m[38;5;124m [39m[38;5;124m"[39m )
[0;32m      5[0m lengdepos [38;5;241m=[39m [[38;5;241m0[39m , [38;5;241m1[39m , [38;5;241m2[39m , [38;5;241m3[39m , [38;5;241m4[39m ,[38;5;241m5[39m , [38;5;241m6[39m , [38;5;241m7[39m , [38;5;241m8[39m, [38;5;241m9[39m, [38;5;241m10[39m, [38;5;241m11[39m]

[1;31mModuleNotFoundError[0m: No module named 'pandas'
ModuleNotFoundError: No module named 'pandas'

